// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Update_user_chirpy_red.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserIsChirpyRed = `-- name: UpdateUserIsChirpyRed :exec
UPDATE users
SET is_chirpy_red = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserIsChirpyRedParams struct {
	IsChirpyRed bool
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateUserIsChirpyRed(ctx context.Context, arg UpdateUserIsChirpyRedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIsChirpyRed, arg.IsChirpyRed, arg.UpdatedAt, arg.ID)
	return err
}
