// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Update_User_Email_Password.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserEmailPassword = `-- name: UpdateUserEmailPassword :exec
UPDATE users
SET email = $1, hashed_password = $2, updated_at = $3
WHERE id = $4
`

type UpdateUserEmailPasswordParams struct {
	Email          string
	HashedPassword string
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdateUserEmailPassword(ctx context.Context, arg UpdateUserEmailPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmailPassword,
		arg.Email,
		arg.HashedPassword,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
